# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-20 15:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='Başlık')),
                ('text', models.TextField(verbose_name='Hikaye')),
                ('category', models.CharField(choices=[('Funny', 'Funny'), ('Mysterious', 'Mysterious')], max_length=15, verbose_name='Kategori')),
                ('language', models.CharField(choices=[('En', 'English'), ('Tr', 'Turkish')], max_length=10, verbose_name='İçerik Dili')),
                ('upvotes', models.IntegerField(default=0, verbose_name='Beğenme')),
                ('downvotes', models.IntegerField(default=0, verbose_name='Beğenmeme')),
                ('urlcode', models.CharField(blank=True, max_length=7, unique=True, verbose_name='Link Kodu')),
                ('active', models.BooleanField(default=True, verbose_name='Yayında')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('reports', models.IntegerField(default=0, verbose_name='Raporlanma')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Stories',
                'ordering': ['created'],
            },
        ),
    ]
