# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-20 15:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'managed': True, 'ordering': ['created'], 'verbose_name_plural': 'Stories'},
        ),
    ]
