# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-20 19:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('story', '0004_story_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=250, verbose_name='Yorum')),
                ('likes', models.IntegerField(default=0, verbose_name='Beğeni')),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
                ('commentator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Yorumcu')),
            ],
            options={
                'verbose_name_plural': 'Hikaye Yorumları',
                'verbose_name': 'Hikaye Yorumu',
                'ordering': ['-comment_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': ['created'], 'verbose_name_plural': 'Stories'},
        ),
        migrations.AddField(
            model_name='story',
            name='popularity',
            field=models.IntegerField(default=0, verbose_name='Populerlik'),
        ),
        migrations.AlterField(
            model_name='story',
            name='author',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Yazar'),
        ),
        migrations.AddField(
            model_name='storycomment',
            name='post_itself',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='story.Story'),
        ),
    ]
