# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-03 23:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0006_auto_20170120_2249'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': ['created'], 'verbose_name': 'Hikaye', 'verbose_name_plural': 'Hikayeler'},
        ),
        migrations.AlterField(
            model_name='story',
            name='popularity',
            field=models.IntegerField(blank=True, verbose_name='Populerlik'),
        ),
        migrations.AlterField(
            model_name='story',
            name='text',
            field=models.TextField(max_length=3000, verbose_name='Hikaye'),
        ),
        migrations.AlterField(
            model_name='storycomment',
            name='post_itself',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='story.Story', verbose_name='Post'),
        ),
    ]
