# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-13 20:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('story', '0007_auto_20170204_0233'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, verbose_name='Gender')),
                ('birthday', models.DateField(blank=True, verbose_name='Birthday')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.AlterField(
            model_name='story',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='story',
            name='author',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='story',
            name='category',
            field=models.CharField(choices=[('Funny', 'Funny'), ('Mysterious', 'Mysterious')], max_length=15, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='story',
            name='downvotes',
            field=models.IntegerField(default=0, verbose_name='Downvotes'),
        ),
        migrations.AlterField(
            model_name='story',
            name='language',
            field=models.CharField(choices=[('En', 'English'), ('Tr', 'Turkish')], max_length=10, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='story',
            name='popularity',
            field=models.IntegerField(blank=True, verbose_name='Popularity'),
        ),
        migrations.AlterField(
            model_name='story',
            name='reports',
            field=models.IntegerField(default=0, verbose_name='Reports'),
        ),
        migrations.AlterField(
            model_name='story',
            name='text',
            field=models.TextField(max_length=3000, verbose_name='Story'),
        ),
        migrations.AlterField(
            model_name='story',
            name='title',
            field=models.CharField(max_length=160, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='story',
            name='upvotes',
            field=models.IntegerField(default=0, verbose_name='Upvotes'),
        ),
        migrations.AlterField(
            model_name='story',
            name='urlcode',
            field=models.CharField(blank=True, max_length=7, unique=True, verbose_name='Link Code'),
        ),
        migrations.AlterField(
            model_name='storycomment',
            name='comment',
            field=models.TextField(max_length=250, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='storycomment',
            name='commentator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Commentator'),
        ),
        migrations.AlterField(
            model_name='storycomment',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='Likes'),
        ),
    ]
