# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-20 18:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0011_auto_20170214_0114'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_text', models.TextField(max_length=300, verbose_name='Report')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='story.Story')),
            ],
        ),
    ]
