# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-20 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0012_postreport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postreport',
            options={'ordering': ['story'], 'verbose_name': 'Post Report'},
        ),
        migrations.AlterModelOptions(
            name='storyupvotes',
            options={'ordering': ['user'], 'verbose_name': 'Story Upvote'},
        ),
        migrations.AddField(
            model_name='postreport',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
