# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-09 00:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('story', '0016_storydownvotes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notifier', models.CharField(max_length=6)),
                ('kind', models.CharField(choices=[('Story', 'Story'), ('Comment', 'Comment')], max_length=8)),
                ('conn', models.CharField(max_length=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
            },
        ),
    ]
