# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-09 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0019_notification_notify_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notify_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
