# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-09 16:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0020_auto_20170309_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='notify_time',
        ),
    ]
