# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0024_auto_20170322_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='secure_key',
            field=models.CharField(max_length=100, null=True, verbose_name='Secure Key'),
        ),
    ]
