# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 17:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0025_story_secure_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='secure_key',
        ),
    ]
