# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 01:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0027_auto_20170327_2339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='downvotes',
        ),
        migrations.RemoveField(
            model_name='story',
            name='reports',
        ),
        migrations.RemoveField(
            model_name='story',
            name='upvotes',
        ),
        migrations.AlterField(
            model_name='story',
            name='popularity',
            field=models.IntegerField(default=0, verbose_name='Popularity'),
        ),
    ]
