# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 01:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0029_auto_20170329_1153'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Votes',
            new_name='Vote',
        ),
        migrations.RemoveField(
            model_name='storydownvotes',
            name='story',
        ),
        migrations.RemoveField(
            model_name='storydownvotes',
            name='user',
        ),
        migrations.RemoveField(
            model_name='storyupvotes',
            name='story',
        ),
        migrations.RemoveField(
            model_name='storyupvotes',
            name='user',
        ),
        migrations.DeleteModel(
            name='StoryDownvotes',
        ),
        migrations.DeleteModel(
            name='StoryUpvotes',
        ),
    ]
