# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 13:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0033_auto_20170331_1357'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='confirmation',
            options={'ordering': ['user'], 'verbose_name': 'Confirmation Key'},
        ),
        migrations.RenameField(
            model_name='confirmation',
            old_name='users',
            new_name='user',
        ),
    ]
