# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-06 04:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0038_auto_20170405_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storycomment',
            name='likes',
        ),
    ]
